INSERT INTO artist (artist_id, artist_name) VALUES ('K8vZ9171uv0', 'Billy Joel');
INSERT INTO artist (artist_id, artist_name) VALUES ('K8vZ9171hM0', 'Bruce Springsteen and The E Street Band');
INSERT INTO artist (artist_id, artist_name) VALUES ('K8vZ9171ug7', 'Bruce Springsteen');
INSERT INTO artist (artist_id, artist_name) VALUES ('K8vZ917KVr7', 'Luke Combs');
INSERT INTO artist (artist_id, artist_name) VALUES ('K8vZ917KUtV', 'Jordan Davis');
INSERT INTO artist (artist_id, artist_name) VALUES ('K8vZ9173lz7', 'Drew Parker');
INSERT INTO artist (artist_id, artist_name) VALUES ('K8vZ917QQSf', 'Colby Acuff');
INSERT INTO artist (artist_id, artist_name) VALUES ('K8vZ917ppwf', 'Mitchell Tenpenny');
INSERT INTO artist (artist_id, artist_name) VALUES ('K8vZ9171Fo7', 'George Strait');
INSERT INTO artist (artist_id, artist_name) VALUES ('K8vZ9178Sb7', 'Chris Stapleton');
INSERT INTO artist (artist_id, artist_name) VALUES ('K8vZ9175ykf', 'Little Big Town');
INSERT INTO artist (artist_id, artist_name) VALUES ('K8vZ917184f', 'The Rolling Stones');
INSERT INTO artist (artist_id, artist_name) VALUES ('K8vZ91713Y7', 'Foo Fighters');
INSERT INTO artist (artist_id, artist_name) VALUES ('K8vZ91713a0', 'The Pretenders');
INSERT INTO artist (artist_id, artist_name) VALUES ('K8vZ917oh_f', 'Alex G');
INSERT INTO artist (artist_id, artist_name) VALUES ('K8vZ917KogV', 'Cody Jinks');
INSERT INTO artist (artist_id, artist_name) VALUES ('K8vZ917b3lf', 'Charles Wesley Godwin');
INSERT INTO artist (artist_id, artist_name) VALUES ('K8vZ917Kj1f', 'Hailey Whitters');
INSERT INTO artist (artist_id, artist_name) VALUES ('K8vZ917_3n7', 'The Wilder Blue');
INSERT INTO artist (artist_id, artist_name) VALUES ('K8vZ9171ajV', 'Luis Miguel');
INSERT INTO artist (artist_id, artist_name) VALUES ('K8vZ9171f30', 'Kenny Chesney');
INSERT INTO artist (artist_id, artist_name) VALUES ('K8vZ9175zn0', 'Zac Brown Band');
INSERT INTO artist (artist_id, artist_name) VALUES ('K8vZ917h8MV', 'Megan Moroney');
INSERT INTO artist (artist_id, artist_name) VALUES ('K8vZ9171wZf', 'Uncle Kracker');
INSERT INTO artist (artist_id, artist_name) VALUES ('K8vZ9171o-f', 'Green Day');
INSERT INTO artist (artist_id, artist_name) VALUES ('K8vZ9171FDV', 'The Smashing Pumpkins');
INSERT INTO artist (artist_id, artist_name) VALUES ('K8vZ9171fW0', 'Rancid');
INSERT INTO artist (artist_id, artist_name) VALUES ('K8vZ917beWV', 'The Linda Lindas');
INSERT INTO artist (artist_id, artist_name) VALUES ('K8vZ9174l1f', 'Bad Bunny');
INSERT INTO artist (artist_id, artist_name) VALUES ('K8vZ9171G9V', 'Metallica');
INSERT INTO artist (artist_id, artist_name) VALUES ('K8vZ91715N7', 'Pantera');
INSERT INTO artist (artist_id, artist_name) VALUES ('K8vZ917_9Z7', 'Mammoth WVH');
INSERT INTO artist (artist_id, artist_name) VALUES ('K8vZ917GCJ7', 'Five Finger Death Punch');
INSERT INTO artist (artist_id, artist_name) VALUES ('K8vZ917uqZ7', 'Ice Nine Kills');
INSERT INTO artist (artist_id, artist_name) VALUES ('K8vZ91712w7', 'Sting');
INSERT INTO artist (artist_id, artist_name) VALUES ('K8vZ9171pNf', 'blink-182');
INSERT INTO artist (artist_id, artist_name) VALUES ('K8vZ917GHdV', 'Pierce The Veil');
INSERT INTO artist (artist_id, artist_name) VALUES ('K8vZ9171_kV', 'CMA Fest');
INSERT INTO artist (artist_id, artist_name) VALUES ('K8vZ9171xeV', 'Shakira');
INSERT INTO artist (artist_id, artist_name) VALUES ('K8vZ9174qlV', 'Morgan Wallen');
INSERT INTO artist (artist_id, artist_name) VALUES ('K8vZ917heVV', 'Lauren Watkins');
INSERT INTO artist (artist_id, artist_name) VALUES ('K8vZ917Q9yV', 'Megan Moroney');
INSERT INTO artist (artist_id, artist_name) VALUES ('K8vZ91715Of', 'L7');
INSERT INTO artist (artist_id, artist_name) VALUES ('K8vZ91757_7', 'The Hives');
INSERT INTO artist (artist_id, artist_name) VALUES ('K8vZ917GgwV', 'The Avett Brothers');
INSERT INTO artist (artist_id, artist_name) VALUES ('K8vZ9179QyV', 'Megan Thee Stallion');
INSERT INTO artist (artist_id, artist_name) VALUES ('Z7r9jZaoLQ', 'GloRilla');
INSERT INTO artist (artist_id, artist_name) VALUES ('K8vZ9171buf', 'Creed');
INSERT INTO artist (artist_id, artist_name) VALUES ('K8vZ9171-m0', '3 Doors Down');
INSERT INTO artist (artist_id, artist_name) VALUES ('K8vZ9171QRf', 'Finger Eleven');
INSERT INTO artist (artist_id, artist_name) VALUES ('K8vZ9171FdV', 'Pearl Jam');
INSERT INTO artist (artist_id, artist_name) VALUES ('K8vZ917ueaV', 'Deep Sea Diver');
INSERT INTO artist (artist_id, artist_name) VALUES ('K8vZ917pDg7', 'Amyl and the Sniffers');
INSERT INTO artist (artist_id, artist_name) VALUES ('K8vZ917fIUf', 'Marcus King');
INSERT INTO artist (artist_id, artist_name) VALUES ('K8vZ917upG0', 'Nikki Lane');
INSERT INTO artist (artist_id, artist_name) VALUES ('K8vZ9171FkV', 'Red Hot Chili Peppers');
INSERT INTO artist (artist_id, artist_name) VALUES ('K8vZfZ7t7ak', 'Ken Carson');
INSERT INTO artist (artist_id, artist_name) VALUES ('K8vZ917KqlV', 'Irontom');
INSERT INTO artist (artist_id, artist_name) VALUES ('K8vZ9171CY7', 'Def Leppard');
INSERT INTO artist (artist_id, artist_name) VALUES ('K8vZ91712F0', 'Journey');
INSERT INTO artist (artist_id, artist_name) VALUES ('K8vZ9175yU7', 'Def Leppard / Journey');
INSERT INTO artist (artist_id, artist_name) VALUES ('K8vZ91712sV', 'Steve Miller Band');
INSERT INTO artist (artist_id, artist_name) VALUES ('K8vZ9171_N0', 'System Of A Down');
INSERT INTO artist (artist_id, artist_name) VALUES ('K8vZ9171pP7', 'Deftones');
INSERT INTO artist (artist_id, artist_name) VALUES ('K8vZ9175_T7', 'The Mars Volta');
INSERT INTO artist (artist_id, artist_name) VALUES ('K8vZ9174rRV', 'Viagra Boys');
INSERT INTO artist (artist_id, artist_name) VALUES ('K8vZ9174sEV', 'VOWWS');
INSERT INTO artist (artist_id, artist_name) VALUES ('K8vZ9179vO0', 'Fuerza Regida');
INSERT INTO artist (artist_id, artist_name) VALUES ('K8vZ917_NoV', 'Zach Bryan');
INSERT INTO artist (artist_id, artist_name) VALUES ('K8vZ91713kV', 'Sheryl Crow');
INSERT INTO artist (artist_id, artist_name) VALUES ('K8vZ917hi4V', 'Levi Turner');
INSERT INTO artist (artist_id, artist_name) VALUES ('K8vZ917bGVf', 'The Middle East');
INSERT INTO artist (artist_id, artist_name) VALUES ('K8vZ917pAzf', 'Noah Kahan');
INSERT INTO artist (artist_id, artist_name) VALUES ('K8vZ917__nf', 'Jensen McRae');
INSERT INTO artist (artist_id, artist_name) VALUES ('K8vZ917C3Cf', 'Glen Hansard');
INSERT INTO artist (artist_id, artist_name) VALUES ('K8vZ9171bMV', 'USHER');
INSERT INTO artist (artist_id, artist_name) VALUES ('K8vZ917C1E0', 'Tedeschi Trucks Band');
INSERT INTO artist (artist_id, artist_name) VALUES ('K8vZ917_Su0', 'Olivia Rodrigo');
INSERT INTO artist (artist_id, artist_name) VALUES ('K8vZ917_TO7', 'PinkPantheress');
INSERT INTO artist (artist_id, artist_name) VALUES ('K8vZ917_T-7', 'ENHYPEN');
INSERT INTO artist (artist_id, artist_name) VALUES ('K8vZ9172PA0', 'Future');
INSERT INTO artist (artist_id, artist_name) VALUES ('K8vZ917KaB7', 'Metro Boomin');
INSERT INTO artist (artist_id, artist_name) VALUES ('K8vZ9171GBV', 'Aerosmith');
INSERT INTO artist (artist_id, artist_name) VALUES ('K8vZ9171uef', 'THE BLACK CROWES');
INSERT INTO artist (artist_id, artist_name) VALUES ('K8vZ9171uU7', 'Cheap Trick');
INSERT INTO artist (artist_id, artist_name) VALUES ('K8vZ9175z5V', 'Aventura');
INSERT INTO artist (artist_id, artist_name) VALUES ('K8vZ917GP27', 'Nicki Minaj');
INSERT INTO artist (artist_id, artist_name) VALUES ('K8vZ9171KpV', 'Monica');
INSERT INTO artist (artist_id, artist_name) VALUES ('K8vZ91712s0', 'Stevie Nicks');
INSERT INTO artist (artist_id, artist_name) VALUES ('K8vZ917pZXV', 'Matt Maeson');
INSERT INTO artist (artist_id, artist_name) VALUES ('K8vZ9171fF7', 'Korn');
INSERT INTO artist (artist_id, artist_name) VALUES ('K8vZ9175430', 'Evanescence');
INSERT INTO artist (artist_id, artist_name) VALUES ('K8vZ9175Hz0', 'Gojira');
INSERT INTO artist (artist_id, artist_name) VALUES ('K8vZ917GGWV', 'Scars On Broadway');
INSERT INTO artist (artist_id, artist_name) VALUES ('K8vZ917_hG0', 'Spiritbox');
INSERT INTO artist (artist_id, artist_name) VALUES ('K8vZfZ7ItFk', 'Vended');
INSERT INTO artist (artist_id, artist_name) VALUES ('K8vZ9174OHV', 'Niall Horan');
INSERT INTO artist (artist_id, artist_name) VALUES ('K8vZ9178ch0', 'Del Water Gap');
INSERT INTO artist (artist_id, artist_name) VALUES ('K8vZ9171Ga0', 'Ice Cube');
INSERT INTO artist (artist_id, artist_name) VALUES ('K8vZ917bcy0', 'Tate McRae');
INSERT INTO artist (artist_id, artist_name) VALUES ('K8vZ917hDN0', 'Presley Regier');
INSERT INTO artist (artist_id, artist_name) VALUES ('K8vZ917CyYf', 'Ryan Beatty');
INSERT INTO artist (artist_id, artist_name) VALUES ('K8vZ917Gft7', 'Kid Cudi');
INSERT INTO artist (artist_id, artist_name) VALUES ('K8vZ917um57', 'Grace Potter');
INSERT INTO artist (artist_id, artist_name) VALUES ('K8vZ917GsJ7', 'Allen Stone');
INSERT INTO artist (artist_id, artist_name) VALUES ('K8vZ917_cQ7', 'Feid');
INSERT INTO artist (artist_id, artist_name) VALUES ('K8vZ91754g7', 'Justin Timberlake');
INSERT INTO artist (artist_id, artist_name) VALUES ('K8vZ917oP4f', 'Melanie Martinez');
INSERT INTO artist (artist_id, artist_name) VALUES ('K8vZ917fEI0', 'Men I Trust');
INSERT INTO artist (artist_id, artist_name) VALUES ('K8vZ9179Vp0', 'Beach Bunny');
INSERT INTO artist (artist_id, artist_name) VALUES ('K8vZ917o-E7', 'Hozier');
INSERT INTO artist (artist_id, artist_name) VALUES ('K8vZ917_be0', 'Allison Russell');
INSERT INTO artist (artist_id, artist_name) VALUES ('K8vZ917CrJV', 'Cincinnati Music Festival presented by P&G');
INSERT INTO artist (artist_id, artist_name) VALUES ('K8vZ9171_Hf', 'Maxwell');
INSERT INTO artist (artist_id, artist_name) VALUES ('K8vZ9175Ho0', 'NE-YO');
INSERT INTO artist (artist_id, artist_name) VALUES ('K8vZ917Cgvf', 'Fantasia');
INSERT INTO artist (artist_id, artist_name) VALUES ('K8vZ917hcof', 'October London');
INSERT INTO artist (artist_id, artist_name) VALUES ('K8vZ9179jI0', 'The Original Lakeside');
INSERT INTO artist (artist_id, artist_name) VALUES ('K8vZ917pay7', 'Tyler Childers');
INSERT INTO artist (artist_id, artist_name) VALUES ('K8vZ917bsF7', 'S.G. Goodman');
INSERT INTO artist (artist_id, artist_name) VALUES ('K8vZ917hhO7', 'Adeem the Artist');
INSERT INTO artist (artist_id, artist_name) VALUES ('K8vZ91715B7', 'New Edition');
INSERT INTO artist (artist_id, artist_name) VALUES ('K8vZ9175r8f', 'Kem');
INSERT INTO artist (artist_id, artist_name) VALUES ('K8vZ917GB2V', 'SWV');
INSERT INTO artist (artist_id, artist_name) VALUES ('K8vZ9174gJ0', 'Stokley');
INSERT INTO artist (artist_id, artist_name) VALUES ('K8vZ917bdF0', 'Tomorrow X Together');
INSERT INTO artist (artist_id, artist_name) VALUES ('K8vZ9175yK0', 'Don Omar');
INSERT INTO artist (artist_id, artist_name) VALUES ('K8vZ91755Zf', 'Avril Lavigne');
INSERT INTO artist (artist_id, artist_name) VALUES ('K8vZ9175egf', 'Simple Plan');
INSERT INTO artist (artist_id, artist_name) VALUES ('K8vZ917uOQV', 'Girlfriends');
INSERT INTO artist (artist_id, artist_name) VALUES ('K8vZ917j460', 'IU');
INSERT INTO artist (artist_id, artist_name) VALUES ('K8vZ917phs0', 'The War and Treaty');
INSERT INTO artist (artist_id, artist_name) VALUES ('K8vZ917fAP7', '21 Savage');
INSERT INTO artist (artist_id, artist_name) VALUES ('K8vZ9174My0', 'J.I.D');
INSERT INTO artist (artist_id, artist_name) VALUES ('K8vZ917_Y_V', 'Nardo Wick');
INSERT INTO artist (artist_id, artist_name) VALUES ('K8vZ917hgiV', '21 Lil Harold');
INSERT INTO artist (artist_id, artist_name) VALUES ('K8vZ9175MQf', 'Chris Brown');
INSERT INTO artist (artist_id, artist_name) VALUES ('K8vZ917QeP0', 'Ayra Starr');
INSERT INTO artist (artist_id, artist_name) VALUES ('K8vZ917_xY7', 'Maeta');
INSERT INTO artist (artist_id, artist_name) VALUES ('K8vZ9173-L7', 'Wand');
INSERT INTO artist (artist_id, artist_name) VALUES ('K8vZ917Kysf', 'Nathaniel Rateliff & The Night Sweats');
INSERT INTO artist (artist_id, artist_name) VALUES ('K8vZ9179Dvf', 'Joy Oladokun');
INSERT INTO artist (artist_id, artist_name) VALUES ('K8vZ917hpSf', 'Bella White');
INSERT INTO artist (artist_id, artist_name) VALUES ('K8vZ9171ajf', 'Los Temerarios');
INSERT INTO artist (artist_id, artist_name) VALUES ('K8vZ917Q5rf', 'Muni Long');
INSERT INTO artist (artist_id, artist_name) VALUES ('K8vZ917Qho7', 'Otoboke Beaver');
INSERT INTO artist (artist_id, artist_name) VALUES ('K8vZ917hs2V', 'Sofia Isella');
INSERT INTO artist (artist_id, artist_name) VALUES ('K8vZ917GJc7', 'Bruno Mars');
INSERT INTO artist (artist_id, artist_name) VALUES ('K8vZ9175g5V', 'The Breeders');
INSERT INTO artist (artist_id, artist_name) VALUES ('K8vZ917Kjxf', 'Wayne Graham');
INSERT INTO artist (artist_id, artist_name) VALUES ('K8vZ9179LdV', 'HARDY');
INSERT INTO artist (artist_id, artist_name) VALUES ('K8vZ9172COf', 'Kip Moore');
INSERT INTO artist (artist_id, artist_name) VALUES ('K8vZ9173oR0', 'Travis Denning');
INSERT INTO artist (artist_id, artist_name) VALUES ('K8vZ9171QAV', 'Joni Mitchell');
INSERT INTO artist (artist_id, artist_name) VALUES ('K8vZ917o6G0', 'SZA');
INSERT INTO artist (artist_id, artist_name) VALUES ('K8vZ917453f', 'Aminé');
INSERT INTO artist (artist_id, artist_name) VALUES ('K8vZ917oeN0', 'James Bay');
INSERT INTO artist (artist_id, artist_name) VALUES ('K8vZ917fFLf', 'Kane Brown');
INSERT INTO artist (artist_id, artist_name) VALUES ('K8vZ917Q0Zf', 'Bailey Zimmerman');
INSERT INTO artist (artist_id, artist_name) VALUES ('K8vZ917Cke7', 'LOCASH');
INSERT INTO artist (artist_id, artist_name) VALUES ('K8vZ917odXf', 'RaeLynn');
INSERT INTO artist (artist_id, artist_name) VALUES ('K8vZ917oEKf', 'ODESZA');
INSERT INTO artist (artist_id, artist_name) VALUES ('K8vZ9178Mc7', 'Bob Moses');
INSERT INTO artist (artist_id, artist_name) VALUES ('K8vZ917_pO7', 'John Summit');
INSERT INTO artist (artist_id, artist_name) VALUES ('Z7r9jZa8OL', 'Muni Long');
INSERT INTO artist (artist_id, artist_name) VALUES ('K8vZ9178Uz0', 'Cody Johnson');
INSERT INTO artist (artist_id, artist_name) VALUES ('K8vZ9174jvf', 'Nova Twins');
INSERT INTO artist (artist_id, artist_name) VALUES ('K8vZ9174y8V', 'Jelly Roll');
INSERT INTO artist (artist_id, artist_name) VALUES ('K8vZ917QK3f', 'Warren Zeiders');
INSERT INTO artist (artist_id, artist_name) VALUES ('K8vZ917_rk0', 'Alexandra Kay');
INSERT INTO artist (artist_id, artist_name) VALUES ('K8vZ917b0Lf', 'John Vincent III');
INSERT INTO artist (artist_id, artist_name) VALUES ('K8vZ9175iO0', 'Miranda Lambert');
INSERT INTO artist (artist_id, artist_name) VALUES ('K8vZ917pt2f', 'Broccoli City Festival');
INSERT INTO artist (artist_id, artist_name) VALUES ('K8vZ917psY7', 'Gunna');
INSERT INTO artist (artist_id, artist_name) VALUES ('K8vZ9174v57', 'Lil Yachty');
INSERT INTO artist (artist_id, artist_name) VALUES ('K8vZ917oX37', 'Partynextdoor');
INSERT INTO artist (artist_id, artist_name) VALUES ('K8vZ917fYD7', 'Victoria Monet');
INSERT INTO artist (artist_id, artist_name) VALUES ('K8vZ917ooF0', 'Kaytranada');
INSERT INTO artist (artist_id, artist_name) VALUES ('K8vZ9179vjf', 'Key Glock');
INSERT INTO artist (artist_id, artist_name) VALUES ('K8vZ917hr8f', 'Sexyy Red');
INSERT INTO artist (artist_id, artist_name) VALUES ('K8vZ917hyqf', 'FRIDAYY');
INSERT INTO artist (artist_id, artist_name) VALUES ('K8vZ917bY2f', 'Veeze');
INSERT INTO artist (artist_id, artist_name) VALUES ('K8vZ917_rW7', 'Teezo Touchdown');
INSERT INTO artist (artist_id, artist_name) VALUES ('K8vZ917f2N7', '$UICIDEBOY$');
INSERT INTO artist (artist_id, artist_name) VALUES ('K8vZ9173Fz7', 'Denzel Curry');
INSERT INTO artist (artist_id, artist_name) VALUES ('K8vZ917u1fV', 'Valerie June');
INSERT INTO artist (artist_id, artist_name) VALUES ('K8vZ917_qH7', 'Willi Carlisle');
INSERT INTO artist (artist_id, artist_name) VALUES ('K8vZ9179YD0', 'Lainey Wilson');
INSERT INTO artist (artist_id, artist_name) VALUES ('K8vZ9179Yef', 'Jackson Dean');
INSERT INTO artist (artist_id, artist_name) VALUES ('K8vZ917hLWV', 'Zach Top');
INSERT INTO artist (artist_id, artist_name) VALUES ('K8vZ9178Ppf', 'Shakey Graves');
INSERT INTO artist (artist_id, artist_name) VALUES ('K8vZ917bZsV', 'Joslyn & The Sweet Compression');
INSERT INTO artist (artist_id, artist_name) VALUES ('K8vZ9174hA7', 'A Boogie Wit Da Hoodie');
INSERT INTO artist (artist_id, artist_name) VALUES ('K8vZ917bdnf', 'NLE Choppa');
INSERT INTO artist (artist_id, artist_name) VALUES ('K8vZ917hfO0', 'Luh Tyler');
INSERT INTO artist (artist_id, artist_name) VALUES ('K8vZ917_yFf', 'Dess Dior');
INSERT INTO artist (artist_id, artist_name) VALUES ('K8vZ91713ZV', 'Brooks & Dunn');
INSERT INTO artist (artist_id, artist_name) VALUES ('K8vZ9171fh0', 'David Lee Murphy');
INSERT INTO artist (artist_id, artist_name) VALUES ('K8vZ9179SG7', 'ERNEST');
INSERT INTO artist (artist_id, artist_name) VALUES ('K8vZ9171Fbf', 'Marty Stuart');
INSERT INTO artist (artist_id, artist_name) VALUES ('K8vZ9179XA0', 'Ben Böhmer');
INSERT INTO artist (artist_id, artist_name) VALUES ('K8vZ9174SG7', 'DRAMA');
INSERT INTO artist (artist_id, artist_name) VALUES ('K8vZ917Khe0', 'Golden Features');
INSERT INTO artist (artist_id, artist_name) VALUES ('K8vZ917G5gV', 'All Time Low');
INSERT INTO artist (artist_id, artist_name) VALUES ('K8vZ917bgpV', 'Royal & the Serpent');
INSERT INTO artist (artist_id, artist_name) VALUES ('K8vZ917GcSf', 'deadmau5');
INSERT INTO artist (artist_id, artist_name) VALUES ('K8vZ917pem0', 'Meute');
INSERT INTO artist (artist_id, artist_name) VALUES ('K8vZ917GnRf', 'Lights');
INSERT INTO artist (artist_id, artist_name) VALUES ('K8vZ917C2XV', 'WTF?');
INSERT INTO artist (artist_id, artist_name) VALUES ('K8vZ9173oIV', 'Kiesza');
INSERT INTO artist (artist_id, artist_name) VALUES ('K8vZ917jlI0', 'Hayla');
INSERT INTO artist (artist_id, artist_name) VALUES ('K8vZ917Cfg7', 'Alex Sensation');
INSERT INTO artist (artist_id, artist_name) VALUES ('K8vZ917bvff', 'Myke Towers');
INSERT INTO artist (artist_id, artist_name) VALUES ('K8vZ917bAj0', 'Eladio Carrion');
INSERT INTO artist (artist_id, artist_name) VALUES ('K8vZ917okqf', 'Arcangel');
INSERT INTO artist (artist_id, artist_name) VALUES ('K8vZ917KNb7', 'Wisin');
INSERT INTO artist (artist_id, artist_name) VALUES ('K8vZ917Qhf7', 'Mora');
INSERT INTO artist (artist_id, artist_name) VALUES ('K8vZ9179NhV', 'Darell');
INSERT INTO artist (artist_id, artist_name) VALUES ('K8vZ917Q4fV', 'Ryan Castro');
INSERT INTO artist (artist_id, artist_name) VALUES ('K8vZ9175Zmf', 'Secreto');
INSERT INTO artist (artist_id, artist_name) VALUES ('K8vZ9171oE7', 'Tim McGraw');
INSERT INTO artist (artist_id, artist_name) VALUES ('K8vZ9172_40', 'Carly Pearce');
INSERT INTO artist (artist_id, artist_name) VALUES ('K8vZ9174Rw0', 'Abby Anderson');
INSERT INTO artist (artist_id, artist_name) VALUES ('K8vZ917CAQV', 'Ed Sheeran');
INSERT INTO artist (artist_id, artist_name) VALUES ('K8vZ91756qf', 'Hot 107.9 Birthday Bash');
INSERT INTO artist (artist_id, artist_name) VALUES ('K8vZ917_glV', 'Latto');
INSERT INTO artist (artist_id, artist_name) VALUES ('K8vZ9175fwV', 'Killer Mike');
INSERT INTO artist (artist_id, artist_name) VALUES ('K8vZ917pkB0', 'Boosie BadAzz');
INSERT INTO artist (artist_id, artist_name) VALUES ('K8vZ917QQw0', 'Hunxho');
INSERT INTO artist (artist_id, artist_name) VALUES ('K8vZ917jfUf', 'BossMan Dlow');
INSERT INTO artist (artist_id, artist_name) VALUES ('K8vZ917Q5r7', 'Rob49');
INSERT INTO artist (artist_id, artist_name) VALUES ('K8vZ9174VxV', 'Tee Grizzley');
INSERT INTO artist (artist_id, artist_name) VALUES ('K8vZ917_fp7', 'Ian Munsick');
INSERT INTO artist (artist_id, artist_name) VALUES ('K8vZ917QER7', 'GloRilla');
INSERT INTO artist (artist_id, artist_name) VALUES ('K8vZ9178_T0', 'Jhene Aiko');
INSERT INTO artist (artist_id, artist_name) VALUES ('K8vZ9179s10', 'Coi Leray');
INSERT INTO artist (artist_id, artist_name) VALUES ('K8vZ917o0Jf', 'Tink');
INSERT INTO artist (artist_id, artist_name) VALUES ('K8vZ917bqMf', 'UMI');
INSERT INTO artist (artist_id, artist_name) VALUES ('K8vZ9179qC0', 'Kiana Ledé');
INSERT INTO artist (artist_id, artist_name) VALUES ('K8vZ917h54V', 'Peso Pluma');
INSERT INTO artist (artist_id, artist_name) VALUES ('K8vZ917G5C0', 'Seun Kuti');
INSERT INTO artist (artist_id, artist_name) VALUES ('K8vZ9171K37', 'Alanis Morissette');
INSERT INTO artist (artist_id, artist_name) VALUES ('K8vZ917uAm0', 'Joan Jett & the Blackhearts');
INSERT INTO artist (artist_id, artist_name) VALUES ('K8vZ917_flV', 'Morgan Wade');
INSERT INTO artist (artist_id, artist_name) VALUES ('K8vZ917Cn97', 'Sammy Hagar');
INSERT INTO artist (artist_id, artist_name) VALUES ('K8vZ9171220', 'Loverboy');
INSERT INTO artist (artist_id, artist_name) VALUES ('K8vZ917CSq0', 'AJR');
INSERT INTO artist (artist_id, artist_name) VALUES ('K8vZ917pNd0', 'Dean Lewis');
INSERT INTO artist (artist_id, artist_name) VALUES ('K8vZ91715ZV', 'Mary J. Blige');
INSERT INTO artist (artist_id, artist_name) VALUES ('K8vZ9175fm7', '50 Cent');
INSERT INTO artist (artist_id, artist_name) VALUES ('K8vZ9171lO7', 'Jill Scott');
INSERT INTO artist (artist_id, artist_name) VALUES ('K8vZ9175df0', 'Fat Joe');
INSERT INTO artist (artist_id, artist_name) VALUES ('K8vZ9171Dj7', 'Jadakiss');
INSERT INTO artist (artist_id, artist_name) VALUES ('K8vZ917hAMf', 'Lola Brooke');
INSERT INTO artist (artist_id, artist_name) VALUES ('K8vZ917Qvnf', 'No Limit Soldiers');
INSERT INTO artist (artist_id, artist_name) VALUES ('K8vZ9171be7', 'Master P');
INSERT INTO artist (artist_id, artist_name) VALUES ('K8vZ9171UiV', 'Silkk the Shocker');
INSERT INTO artist (artist_id, artist_name) VALUES ('K8vZ91741of', 'Mia X');
INSERT INTO artist (artist_id, artist_name) VALUES ('K8vZ9171nV7', 'Fiend');
INSERT INTO artist (artist_id, artist_name) VALUES ('K8vZ917hKBf', 'Mac');
INSERT INTO artist (artist_id, artist_name) VALUES ('K8vZ917QRZV', 'Mr. Serv-On');
INSERT INTO artist (artist_id, artist_name) VALUES ('K8vZ9175V40', 'Webbie');
INSERT INTO artist (artist_id, artist_name) VALUES ('K8vZ917G4u0', 'Luke Bryan');
INSERT INTO artist (artist_id, artist_name) VALUES ('K8vZ917hZ90', 'George Birge');
INSERT INTO artist (artist_id, artist_name) VALUES ('K8vZ917f8G0', 'Dillon Carmichael');
INSERT INTO artist (artist_id, artist_name) VALUES ('K8vZ917btUV', 'Larry Fleet');
INSERT INTO artist (artist_id, artist_name) VALUES ('K8vZ91746CV', 'DJ Rock');
INSERT INTO artist (artist_id, artist_name) VALUES ('K8vZ917GZFf', 'Daughtry');
INSERT INTO artist (artist_id, artist_name) VALUES ('K8vZ9171b9f', 'Fuel (USA)');
INSERT INTO artist (artist_id, artist_name) VALUES ('K8vZ9171fb0', 'Vertical Horizon');
INSERT INTO artist (artist_id, artist_name) VALUES ('K8vZ91713g7', 'The Verve Pipe');
INSERT INTO artist (artist_id, artist_name) VALUES ('K8vZ917G_If', 'Justin Moore');
INSERT INTO artist (artist_id, artist_name) VALUES ('K8vZ917QmdV', 'Drake Milligan');
INSERT INTO artist (artist_id, artist_name) VALUES ('K8vZ9172SV0', 'Chris Janson');
INSERT INTO artist (artist_id, artist_name) VALUES ('K8vZ917Qjw0', 'Benson Boone');
INSERT INTO artist (artist_id, artist_name) VALUES ('K8vZ917__Q0', 'Mimi Webb');
INSERT INTO artist (artist_id, artist_name) VALUES ('K8vZ917K9G0', 'Diljit Dosanjh');
INSERT INTO artist (artist_id, artist_name) VALUES ('K8vZ9173Pzf', 'Buffalo Wabs & the Price Hill Hustle');
INSERT INTO artist (artist_id, artist_name) VALUES ('K8vZ917_PHV', 'Alana Springsteen');
INSERT INTO artist (artist_id, artist_name) VALUES ('K8vZ917QKSV', 'Chase Matthew');
INSERT INTO artist (artist_id, artist_name) VALUES ('K8vZ917Qlz7', 'HunterGirl');
INSERT INTO artist (artist_id, artist_name) VALUES ('K8vZ917bY9V', 'Grupo Firme');
INSERT INTO artist (artist_id, artist_name) VALUES ('K8vZ91713uV', 'The Offspring');
INSERT INTO artist (artist_id, artist_name) VALUES ('K8vZ9171cz7', 'Chevelle');
INSERT INTO artist (artist_id, artist_name) VALUES ('K8vZ917u750', 'Motionless In White');
INSERT INTO artist (artist_id, artist_name) VALUES ('K8vZ9171P17', 'P.O.D.');
INSERT INTO artist (artist_id, artist_name) VALUES ('K8vZ917p-J0', 'Bad Wolves');
INSERT INTO artist (artist_id, artist_name) VALUES ('K8vZ917hyy0', 'Bury the Darkness');
INSERT INTO artist (artist_id, artist_name) VALUES ('K8vZ917Kkx0', 'Mitski');
INSERT INTO artist (artist_id, artist_name) VALUES ('K8vZ917_Qv0', 'Laufey');
INSERT INTO artist (artist_id, artist_name) VALUES ('K8vZ917pAm7', 'All Things Go Music Festival');
INSERT INTO artist (artist_id, artist_name) VALUES ('K8vZ917heM7', 'Reneé Rapp');
INSERT INTO artist (artist_id, artist_name) VALUES ('K8vZ9179_07', 'Conan Gray');
INSERT INTO artist (artist_id, artist_name) VALUES ('K8vZ917p56f', 'Chappell Roan');
INSERT INTO artist (artist_id, artist_name) VALUES ('K8vZ917KWbV', 'Maren Morris');
INSERT INTO artist (artist_id, artist_name) VALUES ('K8vZ917KHgf', 'The Japanese House');
INSERT INTO artist (artist_id, artist_name) VALUES ('K8vZ917bb97', 'Holly Humberstone');
INSERT INTO artist (artist_id, artist_name) VALUES ('K8vZ917QEzV', 'David Kushner');
INSERT INTO artist (artist_id, artist_name) VALUES ('K8vZ917bGS0', 'flipturn');
INSERT INTO artist (artist_id, artist_name) VALUES ('K8vZ917pwSf', 'Soccer Mommy');
INSERT INTO artist (artist_id, artist_name) VALUES ('K8vZ917hkF7', 'Medium Build');
INSERT INTO artist (artist_id, artist_name) VALUES ('K8vZ917QVQf', 'Blondshell');
INSERT INTO artist (artist_id, artist_name) VALUES ('K8vZ917_Njf', 'Lola Young');
INSERT INTO artist (artist_id, artist_name) VALUES ('K8vZ917bwJf', 'Infinity Song');
INSERT INTO artist (artist_id, artist_name) VALUES ('K8vZ917hrhV', 'Towa Bird');
INSERT INTO artist (artist_id, artist_name) VALUES ('K8vZ917h_dV', 'Sadurn');
INSERT INTO artist (artist_id, artist_name) VALUES ('K8vZ917QeQ7', 'Abby Roberts');
INSERT INTO artist (artist_id, artist_name) VALUES ('K8vZ917ubK0', 'Hans Zimmer');
INSERT INTO artist (artist_id, artist_name) VALUES ('K8vZ917GPQ7', 'Chris Young');
INSERT INTO artist (artist_id, artist_name) VALUES ('K8vZ9171GRV', 'New Kids On the Block');
INSERT INTO artist (artist_id, artist_name) VALUES ('K8vZ9171577', 'Paula Abdul');
INSERT INTO artist (artist_id, artist_name) VALUES ('K8vZ917CP8V', 'DJ Jazzy Jeff');
INSERT INTO artist (artist_id, artist_name) VALUES ('Z7r9jZaobe', 'Chappell Roan');
INSERT INTO artist (artist_id, artist_name) VALUES ('K8vZ917QfBf', 'Brandon Lake');
INSERT INTO artist (artist_id, artist_name) VALUES ('K8vZ917bUWf', 'DOE');
INSERT INTO artist (artist_id, artist_name) VALUES ('K8vZ9173QDf', 'King Gizzard and the Lizard Wizard');
INSERT INTO artist (artist_id, artist_name) VALUES ('K8vZ917_6ef', 'Geese');
INSERT INTO artist (artist_id, artist_name) VALUES ('K8vZ9172zj0', 'Kevin Gates');
INSERT INTO artist (artist_id, artist_name) VALUES ('K8vZ9171580', 'Cypress Hill');
INSERT INTO artist (artist_id, artist_name) VALUES ('K8vZ9171nUV', 'Bone Thugs-N-Harmony');
INSERT INTO artist (artist_id, artist_name) VALUES ('K8vZ9171tk7', 'Three 6 Mafia');
INSERT INTO artist (artist_id, artist_name) VALUES ('K8vZ9171Vjf', 'Ghostface Killah');
INSERT INTO artist (artist_id, artist_name) VALUES ('K8vZ9172-Yf', 'Berner');
INSERT INTO artist (artist_id, artist_name) VALUES ('K8vZ9171j-V', 'Dilated Peoples');
INSERT INTO artist (artist_id, artist_name) VALUES ('K8vZ91714lV', 'The Pharcyde');
INSERT INTO artist (artist_id, artist_name) VALUES ('K8vZ917Cum0', 'The Psycho Realm');
INSERT INTO artist (artist_id, artist_name) VALUES ('K8vZ917QEF0', 'Tyler Hubbard');
INSERT INTO artist (artist_id, artist_name) VALUES ('K8vZ9175U20', 'Carrie Underwood');
INSERT INTO artist (artist_id, artist_name) VALUES ('K8vZ917jpu7', 'Landon Parker');
INSERT INTO artist (artist_id, artist_name) VALUES ('K8vZ917pUdV', 'Outlaw Music Festival');
INSERT INTO artist (artist_id, artist_name) VALUES ('K8vZ9171aKV', 'Willie Nelson');
INSERT INTO artist (artist_id, artist_name) VALUES ('K8vZ9171ueV', 'Bob Dylan');
INSERT INTO artist (artist_id, artist_name) VALUES ('K8vZ91712kf', 'John Mellencamp');
INSERT INTO artist (artist_id, artist_name) VALUES ('K8vZ9174G2V', 'Billy Strings');
INSERT INTO artist (artist_id, artist_name) VALUES ('K8vZ917_9n7', 'Brittney Spencer');
INSERT INTO artist (artist_id, artist_name) VALUES ('K8vZ9171C8V', 'HEART');
INSERT INTO artist (artist_id, artist_name) VALUES ('K8vZ917ofYf', 'Sylvan Esso');
INSERT INTO artist (artist_id, artist_name) VALUES ('K8vZ917KEwV', 'NF');
INSERT INTO artist (artist_id, artist_name) VALUES ('K8vZ917ukw7', 'Twenty One Pilots');
INSERT INTO artist (artist_id, artist_name) VALUES ('K8vZ917hyNV', 'Oliver Anthony');
INSERT INTO artist (artist_id, artist_name) VALUES ('K8vZ917G1D7', 'Vampire Weekend');
INSERT INTO artist (artist_id, artist_name) VALUES ('K8vZ917GWN0', 'The English Beat');
INSERT INTO artist (artist_id, artist_name) VALUES ('K8vZ91719JV', 'Voodoo Glow Skulls');
INSERT INTO artist (artist_id, artist_name) VALUES ('K8vZ917hKR0', 'Stephen Wilson Jr.');
INSERT INTO artist (artist_id, artist_name) VALUES ('K8vZ9175DZ7', 'Mark Ronson');
INSERT INTO artist (artist_id, artist_name) VALUES ('K8vZ917blT7', 'Turnstiles');
INSERT INTO artist (artist_id, artist_name) VALUES ('K8vZ917fN6V', 'Cigarettes After Sex');
INSERT INTO artist (artist_id, artist_name) VALUES ('K8vZ917112V', 'Caifanes');
INSERT INTO artist (artist_id, artist_name) VALUES ('K8vZ9171rI7', 'Café Tacvba');
INSERT INTO artist (artist_id, artist_name) VALUES ('K8vZ917bF-7', 'mxmtoon');
INSERT INTO artist (artist_id, artist_name) VALUES ('K8vZ917bktV', 'Almost Monday');
INSERT INTO artist (artist_id, artist_name) VALUES ('K8vZ91712y7', 'Toto');
INSERT INTO artist (artist_id, artist_name) VALUES ('K8vZ917__9f', 'Flo Milli');
INSERT INTO artist (artist_id, artist_name) VALUES ('K8vZ917pq90', 'Maisie Peters');
INSERT INTO artist (artist_id, artist_name) VALUES ('K8vZ91759Zf', 'The Postal Service');
INSERT INTO artist (artist_id, artist_name) VALUES ('K8vZ9171NGf', 'Death Cab for Cutie');
INSERT INTO artist (artist_id, artist_name) VALUES ('K8vZ917bK5V', 'Slow Pulp');
INSERT INTO artist (artist_id, artist_name) VALUES ('K8vZ917u_4V', 'Pouya');
INSERT INTO artist (artist_id, artist_name) VALUES ('K8vZ917Qch0', 'Haarper');
INSERT INTO artist (artist_id, artist_name) VALUES ('K8vZ917p7K7', 'Shakewell');
INSERT INTO artist (artist_id, artist_name) VALUES ('K8vZ917_sp7', 'Ekkstacy');
INSERT INTO artist (artist_id, artist_name) VALUES ('K8vZ9171u0V', 'Chicago');
INSERT INTO artist (artist_id, artist_name) VALUES ('K8vZ91711UV', 'Earth, Wind & Fire');
INSERT INTO artist (artist_id, artist_name) VALUES ('K8vZ917b6M7', 'Polo G');
INSERT INTO artist (artist_id, artist_name) VALUES ('K8vZ917b7o0', '42 Dugg');
INSERT INTO artist (artist_id, artist_name) VALUES ('K8vZ917jPJ0', 'JT');
INSERT INTO artist (artist_id, artist_name) VALUES ('K8vZ917fk_7', 'G Herbo');
INSERT INTO artist (artist_id, artist_name) VALUES ('K8vZ917QgL0', 'Skilla Baby');
INSERT INTO artist (artist_id, artist_name) VALUES ('K8vZ917_WfV', 'Big Boogie');
INSERT INTO artist (artist_id, artist_name) VALUES ('K8vZ917jPJV', 'Mello Buckzz');
INSERT INTO artist (artist_id, artist_name) VALUES ('K8vZ917_mB0', 'Ella Langley');
INSERT INTO artist (artist_id, artist_name) VALUES ('K8vZ917G1zf', 'Cage The Elephant');
INSERT INTO artist (artist_id, artist_name) VALUES ('K8vZ917GU-V', 'Young the Giant');
INSERT INTO artist (artist_id, artist_name) VALUES ('K8vZ917pM7V', 'Bakar');
INSERT INTO artist (artist_id, artist_name) VALUES ('K8vZ91738o0', 'Greta Van Fleet');
INSERT INTO artist (artist_id, artist_name) VALUES ('K8vZ917hjg0', 'Wasia Project');
INSERT INTO artist (artist_id, artist_name) VALUES ('K8vZ917hK27', 'Kelce Jam');
INSERT INTO artist (artist_id, artist_name) VALUES ('K8vZ917GemV', 'Lil Wayne');
INSERT INTO artist (artist_id, artist_name) VALUES ('K8vZ917G2o7', 'Diplo');
INSERT INTO artist (artist_id, artist_name) VALUES ('K8vZ917CiQV', '2 Chainz');
INSERT INTO artist (artist_id, artist_name) VALUES ('K8vZ91726_V', 'DJ Irie');
INSERT INTO artist (artist_id, artist_name) VALUES ('K8vZ9178plV', 'E-V');
INSERT INTO artist (artist_id, artist_name) VALUES ('K8vZ9175YVV', 'Jesse McCartney');
INSERT INTO artist (artist_id, artist_name) VALUES ('K8vZ9178es0', 'Neil Young & Crazy Horse');
INSERT INTO artist (artist_id, artist_name) VALUES ('K8vZ91712r0', 'Neil Young');
INSERT INTO artist (artist_id, artist_name) VALUES ('K8vZ917bF5V', 'Pouya');
INSERT INTO artist (artist_id, artist_name) VALUES ('K8vZ917_p7V', 'Bruno Mars Las Vegas');
INSERT INTO artist (artist_id, artist_name) VALUES ('K8vZ917GET0', 'Cults');
INSERT INTO artist (artist_id, artist_name) VALUES ('K8vZ917bnP0', 'Teddy Swims');
INSERT INTO artist (artist_id, artist_name) VALUES ('K8vZ917bg5f', 'Kameron Marlowe');
INSERT INTO artist (artist_id, artist_name) VALUES ('K8vZ917_bFf', 'Chayce Beckham');
INSERT INTO artist (artist_id, artist_name) VALUES ('K8vZ917463V', 'Southern Avenue');
INSERT INTO artist (artist_id, artist_name) VALUES ('K8vZ917CCl7', 'Banda MS');
INSERT INTO artist (artist_id, artist_name) VALUES ('K8vZ9171BQ0', 'Bunbury');
INSERT INTO artist (artist_id, artist_name) VALUES ('K8vZ917hYJV', 'Sessanta');
INSERT INTO artist (artist_id, artist_name) VALUES ('K8vZ9171FBf', 'Primus');
INSERT INTO artist (artist_id, artist_name) VALUES ('K8vZ917CTE0', 'Puscifer');
INSERT INTO artist (artist_id, artist_name) VALUES ('K8vZ9171rq0', 'A Perfect Circle');
INSERT INTO artist (artist_id, artist_name) VALUES ('K8vZ917_0l0', 'Marca MP');
INSERT INTO artist (artist_id, artist_name) VALUES ('K8vZ917hmMf', 'Gabito Ballesteros');
INSERT INTO artist (artist_id, artist_name) VALUES ('K8vZ917jCQV', 'Chino Pacas');
INSERT INTO artist (artist_id, artist_name) VALUES ('K8vZ917KYU0', 'Dead & Company');
INSERT INTO artist (artist_id, artist_name) VALUES ('K8vZ9178q_7', 'Jeff Lynne''s ELO');
INSERT INTO artist (artist_id, artist_name) VALUES ('K8vZ917b81f', 'Sleep Token');
INSERT INTO artist (artist_id, artist_name) VALUES ('K8vZ917hC9f', 'Empire State Bastard');
INSERT INTO artist (artist_id, artist_name) VALUES ('K8vZ9175zpV', 'Jason Aldean');
INSERT INTO artist (artist_id, artist_name) VALUES ('K8vZ917hoeV', 'Austin Snell');
INSERT INTO artist (artist_id, artist_name) VALUES ('K8vZ9178r30', 'Dee Jay Silver');
INSERT INTO artist (artist_id, artist_name) VALUES ('K8vZ917GAT7', 'Jennifer Lopez');
INSERT INTO artist (artist_id, artist_name) VALUES ('K8vZ917Q4f7', 'Ethel Cain');
INSERT INTO artist (artist_id, artist_name) VALUES ('K8vZ917hsTV', 'Alofoke');
INSERT INTO artist (artist_id, artist_name) VALUES ('K8vZ91713gf', 'Weezer');
INSERT INTO artist (artist_id, artist_name) VALUES ('K8vZ91716g7', 'The Flaming Lips');
INSERT INTO artist (artist_id, artist_name) VALUES ('K8vZ91716S0', 'Dinosaur Jr.');
INSERT INTO artist (artist_id, artist_name) VALUES ('K8vZ91719nV', 'Essence Festival of Culture');
INSERT INTO artist (artist_id, artist_name) VALUES ('K8vZ9179bO7', 'Tinlicker');
INSERT INTO artist (artist_id, artist_name) VALUES ('K8vZ9173GO7', 'Bleachers');
INSERT INTO artist (artist_id, artist_name) VALUES ('K8vZ9171b80', 'Save Ferris');
INSERT INTO artist (artist_id, artist_name) VALUES ('K8vZ9174O-f', 'NIGHTLY');
INSERT INTO artist (artist_id, artist_name) VALUES ('K8vZ9174027', 'Maggie Rogers');
INSERT INTO artist (artist_id, artist_name) VALUES ('K8vZ9171b3V', 'Ween');
INSERT INTO artist (artist_id, artist_name) VALUES ('K8vZ917jp77', 'Byron Messia');
INSERT INTO artist (artist_id, artist_name) VALUES ('K8vZ9171jWV', 'Frankie Beverly');
INSERT INTO artist (artist_id, artist_name) VALUES ('K8vZ91715U0', 'Maze');
INSERT INTO artist (artist_id, artist_name) VALUES ('K8vZ91715df', 'The O''Jays');
INSERT INTO artist (artist_id, artist_name) VALUES ('K8vZ91714if', 'The Whispers');
INSERT INTO artist (artist_id, artist_name) VALUES ('K8vZ91780bf', 'Artikal Sound System');
INSERT INTO artist (artist_id, artist_name) VALUES ('K8vZ9171CFf', 'Eric Clapton');
INSERT INTO artist (artist_id, artist_name) VALUES ('K8vZ9171o00', 'Jimmie Vaughan');
INSERT INTO artist (artist_id, artist_name) VALUES ('K8vZ9171oJV', 'Hootie & the Blowfish');
INSERT INTO artist (artist_id, artist_name) VALUES ('K8vZ91713m0', 'Collective Soul');
INSERT INTO artist (artist_id, artist_name) VALUES ('K8vZ9171KD7', 'Edwin McCain');
INSERT INTO artist (artist_id, artist_name) VALUES ('K8vZ9171ORf', 'Staind');
INSERT INTO artist (artist_id, artist_name) VALUES ('K8vZ917K5Nf', 'I Prevail');
INSERT INTO artist (artist_id, artist_name) VALUES ('K8vZ917GI6V', 'Asking Alexandria');
INSERT INTO artist (artist_id, artist_name) VALUES ('K8vZ917Kvqf', 'Dayseeker');
INSERT INTO artist (artist_id, artist_name) VALUES ('K8vZ9178oPV', 'Tim Montana');
INSERT INTO artist (artist_id, artist_name) VALUES ('Z7r9jZa8q6', 'The Linda Lindas');
INSERT INTO artist (artist_id, artist_name) VALUES ('K8vZ917obtV', 'Cole Swindell');
INSERT INTO artist (artist_id, artist_name) VALUES ('K8vZ9173V70', 'ILLENIUM');
INSERT INTO artist (artist_id, artist_name) VALUES ('K8vZ9173hY0', 'Hatsune Miku');
INSERT INTO artist (artist_id, artist_name) VALUES ('K8vZ91713NV', 'Dave Matthews Band');
INSERT INTO artist (artist_id, artist_name) VALUES ('K8vZ9171bff', 'Missy Elliott');
INSERT INTO artist (artist_id, artist_name) VALUES ('K8vZ9175Rm7', 'Ciara');
INSERT INTO artist (artist_id, artist_name) VALUES ('K8vZ9171Ql0', 'Busta Rhymes');
INSERT INTO artist (artist_id, artist_name) VALUES ('K8vZ917GGbf', 'Timbaland');
INSERT INTO artist (artist_id, artist_name) VALUES ('K8vZ917bgyV', 'Legends Day');
INSERT INTO artist (artist_id, artist_name) VALUES ('K8vZ9173IbV', 'Riley Green');
INSERT INTO artist (artist_id, artist_name) VALUES ('K8vZ9178qO7', 'Parmalee');
INSERT INTO artist (artist_id, artist_name) VALUES ('K8vZ917hqF7', 'Phil Wickham & Brandon Lake');
INSERT INTO artist (artist_id, artist_name) VALUES ('K8vZ917h_n0', 'Hulvey');
INSERT INTO artist (artist_id, artist_name) VALUES ('K8vZ91715w7', 'Janet Jackson');
INSERT INTO artist (artist_id, artist_name) VALUES ('K8vZ9171Yef', 'Nelly');
INSERT INTO artist (artist_id, artist_name) VALUES ('K8vZ9178JBf', 'Jon Foreman');
INSERT INTO artist (artist_id, artist_name) VALUES ('K8vZ9171fjV', 'Terri Clark');
INSERT INTO artist (artist_id, artist_name) VALUES ('K8vZ917GSwV', 'Janelle Monáe');
INSERT INTO artist (artist_id, artist_name) VALUES ('K8vZ917b-ZV', 'Remi Wolf');
INSERT INTO artist (artist_id, artist_name) VALUES ('K8vZ917fa5V', 'Julien Baker');
INSERT INTO artist (artist_id, artist_name) VALUES ('K8vZ917CBt7', 'Michael Kiwanuka');
INSERT INTO artist (artist_id, artist_name) VALUES ('K8vZ9173zX7', 'Briston Maroney');
INSERT INTO artist (artist_id, artist_name) VALUES ('K8vZ917hu8V', 'Sammy Rae & The Friends');
INSERT INTO artist (artist_id, artist_name) VALUES ('K8vZ9172pgf', 'Mannequin Pussy');
INSERT INTO artist (artist_id, artist_name) VALUES ('K8vZ917basV', 'Indigo De Souza');
INSERT INTO artist (artist_id, artist_name) VALUES ('K8vZ917Qne7', 'grentperez');
INSERT INTO artist (artist_id, artist_name) VALUES ('K8vZ9179iX7', 'Rachel Chinouriri');
INSERT INTO artist (artist_id, artist_name) VALUES ('K8vZ917_NsV', 'Annie DiRusso');
INSERT INTO artist (artist_id, artist_name) VALUES ('K8vZ917_pu0', 'Allison Ponthier');
INSERT INTO artist (artist_id, artist_name) VALUES ('K8vZ917_Wb7', 'Oliver Malcolm');
INSERT INTO artist (artist_id, artist_name) VALUES ('K8vZ9173XHf', 'Russ');
INSERT INTO artist (artist_id, artist_name) VALUES ('K8vZ9174IH0', '6LACK');
INSERT INTO artist (artist_id, artist_name) VALUES ('K8vZ9179IUf', 'Melii');
INSERT INTO artist (artist_id, artist_name) VALUES ('K8vZ917GA77', 'Unkle');
INSERT INTO artist (artist_id, artist_name) VALUES ('K8vZ9172Ca0', 'Kacey Musgraves');
INSERT INTO artist (artist_id, artist_name) VALUES ('K8vZ9172jSV', 'Father John Misty');
INSERT INTO artist (artist_id, artist_name) VALUES ('K8vZ9171Eb7', 'Nickel Creek');
INSERT INTO artist (artist_id, artist_name) VALUES ('K8vZ917j4x0', 'Codiciado');
INSERT INTO artist (artist_id, artist_name) VALUES ('K8vZ9175WR0', 'Chris Tomlin');
INSERT INTO artist (artist_id, artist_name) VALUES ('K8vZfZ7tFAk', 'CAIN');
