INSERT INTO state (state_name, state_code, country_name, country_code) VALUES ('New York', 'NY', 'United States Of America', 'US');
INSERT INTO state (state_name, state_code, country_name, country_code) VALUES ('District of Columbia', 'DC', 'United States Of America', 'US');
INSERT INTO state (state_name, state_code, country_name, country_code) VALUES ('California', 'CA', 'United States Of America', 'US');
INSERT INTO state (state_name, state_code, country_name, country_code) VALUES ('Utah', 'UT', 'United States Of America', 'US');
INSERT INTO state (state_name, state_code, country_name, country_code) VALUES ('Washington', 'WA', 'United States Of America', 'US');
INSERT INTO state (state_name, state_code, country_name, country_code) VALUES ('Texas', 'TX', 'United States Of America', 'US');
INSERT INTO state (state_name, state_code, country_name, country_code) VALUES ('Maryland', 'MD', 'United States Of America', 'US');
INSERT INTO state (state_name, state_code, country_name, country_code) VALUES ('Georgia', 'GA', 'United States Of America', 'US');
INSERT INTO state (state_name, state_code, country_name, country_code) VALUES ('New Jersey', 'NJ', 'United States Of America', 'US');
INSERT INTO state (state_name, state_code, country_name, country_code) VALUES ('Minnesota', 'MN', 'United States Of America', 'US');
INSERT INTO state (state_name, state_code, country_name, country_code) VALUES ('Missouri', 'MO', 'United States Of America', 'US');
INSERT INTO state (state_name, state_code, country_name, country_code) VALUES ('Pennsylvania', 'PA', 'United States Of America', 'US');
INSERT INTO state (state_name, state_code, country_name, country_code) VALUES ('Tennessee', 'TN', 'United States Of America', 'US');
INSERT INTO state (state_name, state_code, country_name, country_code) VALUES ('Ohio', 'OH', 'United States Of America', 'US');
INSERT INTO state (state_name, state_code, country_name, country_code) VALUES ('Virginia', 'VA', 'United States Of America', 'US');
INSERT INTO state (state_name, state_code, country_name, country_code) VALUES ('Colorado', 'CO', 'United States Of America', 'US');
INSERT INTO state (state_name, state_code, country_name, country_code) VALUES ('Nevada', 'NV', 'United States Of America', 'US');
INSERT INTO state (state_name, state_code, country_name, country_code) VALUES ('Illinois', 'IL', 'United States Of America', 'US');
INSERT INTO state (state_name, state_code, country_name, country_code) VALUES ('Michigan', 'MI', 'United States Of America', 'US');
INSERT INTO state (state_name, state_code, country_name, country_code) VALUES ('Wisconsin', 'WI', 'United States Of America', 'US');
INSERT INTO state (state_name, state_code, country_name, country_code) VALUES ('Florida', 'FL', 'United States Of America', 'US');
INSERT INTO state (state_name, state_code, country_name, country_code) VALUES ('Arizona', 'AZ', 'United States Of America', 'US');
INSERT INTO state (state_name, state_code, country_name, country_code) VALUES ('North Carolina', 'NC', 'United States Of America', 'US');
INSERT INTO state (state_name, state_code, country_name, country_code) VALUES ('Oregon', 'OR', 'United States Of America', 'US');
INSERT INTO state (state_name, state_code, country_name, country_code) VALUES ('Oklahoma', 'OK', 'United States Of America', 'US');
INSERT INTO state (state_name, state_code, country_name, country_code) VALUES ('Massachusetts', 'MA', 'United States Of America', 'US');
INSERT INTO state (state_name, state_code, country_name, country_code) VALUES ('Indiana', 'IN', 'United States Of America', 'US');
INSERT INTO state (state_name, state_code, country_name, country_code) VALUES ('North Dakota', 'ND', 'United States Of America', 'US');
INSERT INTO state (state_name, state_code, country_name, country_code) VALUES ('South Carolina', 'SC', 'United States Of America', 'US');
INSERT INTO state (state_name, state_code, country_name, country_code) VALUES ('Nebraska', 'NE', 'United States Of America', 'US');
INSERT INTO state (state_name, state_code, country_name, country_code) VALUES ('Louisiana', 'LA', 'United States Of America', 'US');
INSERT INTO state (state_name, state_code, country_name, country_code) VALUES ('Kansas', 'KS', 'United States Of America', 'US');
INSERT INTO state (state_name, state_code, country_name, country_code) VALUES ('New Mexico', 'NM', 'United States Of America', 'US');
INSERT INTO state (state_name, state_code, country_name, country_code) VALUES ('Kentucky', 'KY', 'United States Of America', 'US');
INSERT INTO state (state_name, state_code, country_name, country_code) VALUES ('Arkansas', 'AR', 'United States Of America', 'US');
INSERT INTO state (state_name, state_code, country_name, country_code) VALUES ('New Hampshire', 'NH', 'United States Of America', 'US');
INSERT INTO state (state_name, state_code, country_name, country_code) VALUES ('Alabama', 'AL', 'United States Of America', 'US');
INSERT INTO state (state_name, state_code, country_name, country_code) VALUES ('Connecticut', 'CT', 'United States Of America', 'US');
INSERT INTO state (state_name, state_code, country_name, country_code) VALUES ('Maine', 'ME', 'United States Of America', 'US');
INSERT INTO state (state_name, state_code, country_name, country_code) VALUES ('Idaho', 'ID', 'United States Of America', 'US');
INSERT INTO state (state_name, state_code, country_name, country_code) VALUES ('Mississippi', 'MS', 'United States Of America', 'US');
